name: app_store_1
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.1.0-213.0.dev <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  # Icon
  cupertino_icons: ^1.0.2
  # UI Responsive
  flutter_screenutil: ^5.8.4
  # Font Family
  google_fonts: ^5.1.0
  # svg
  flutter_svg: ^2.0.7
  # language
  easy_localization: ^3.0.2
  # Manage State
  provider: ^6.0.5
  # save locale data
  shared_preferences: ^2.2.0
   # webview
  webview_flutter: ^4.2.2
  # http Client 
  http: ^1.1.0
  # Validate Forms
  validators: ^3.0.0
  # Firebase Packages
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/lang/
    # assets fonts
fonts:
  - family: start
    fonts:
      - asset: assets/fonts/start.ttf
  - family: parisienne
    fonts:
      - asset: assets/fonts/parisienne.ttf
              