// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPuqDux1sGaFPQzX9gkZgUMCY5sAPwx24',
    appId: '1:688840431282:web:557d2c91232b7ae6121bab',
    messagingSenderId: '688840431282',
    projectId: 'app-store-1-287a5',
    authDomain: 'app-store-1-287a5.firebaseapp.com',
    storageBucket: 'app-store-1-287a5.appspot.com',
    measurementId: 'G-PD1EMWCHZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfWeCN7z9-0GACZYY0gydNNyWl6sL4SHE',
    appId: '1:688840431282:android:13baa73d4237824e121bab',
    messagingSenderId: '688840431282',
    projectId: 'app-store-1-287a5',
    storageBucket: 'app-store-1-287a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQnR_d_uBjyGsJHa6qjD433oJb-9FvCVc',
    appId: '1:688840431282:ios:6093583401bb1892121bab',
    messagingSenderId: '688840431282',
    projectId: 'app-store-1-287a5',
    storageBucket: 'app-store-1-287a5.appspot.com',
    iosClientId: '688840431282-k3fo94pi28jnr95ifal3pg7t902kpfrr.apps.googleusercontent.com',
    iosBundleId: 'com.example.appStore1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQnR_d_uBjyGsJHa6qjD433oJb-9FvCVc',
    appId: '1:688840431282:ios:c6a5d74babe0643e121bab',
    messagingSenderId: '688840431282',
    projectId: 'app-store-1-287a5',
    storageBucket: 'app-store-1-287a5.appspot.com',
    iosClientId: '688840431282-6tkop4068h5u39ggbhjmncsqns5vnoot.apps.googleusercontent.com',
    iosBundleId: 'com.example.appStore1.RunnerTests',
  );
}
